import {
  Armchair,
  BadgePercent,
  Banknote,
  Bike,
  BookOpen,
  Boxes,
  Calculator,
  ChartNoAxesColumnIncreasing,
  ChefHat,
  Check,
  CircleCheckBig,
  CircleX,
  ClipboardList,
  CreditCard,
  FileText,
  HandCoins,
  Hourglass,
  KeyRound,
  Link2,
  LockKeyhole,
  Mail,
  MapPinned,
  Martini,
  MessageSquare,
  Minus,
  Monitor,
  NotebookPen,
  Package,
  PartyPopper,
  Plus,
  Printer,
  Puzzle,
  Receipt,
  RefreshCw,
  Sandwich,
  Scissors,
  Sheet,
  ShieldCheck,
  ShoppingBag,
  Smartphone,
  Sparkles,
  Store,
  Table2,
  Tag,
  TriangleAlert,
  UserCog,
  Users,
  Wallet,
  WifiOff,
  X,
  Zap
} from 'lucide-svelte';

const iconMap = {
  '⚡': Zap,
  '📒': NotebookPen,
  '📦': Boxes,
  '💰': Wallet,
  '📲': Smartphone,
  '🍔': Sandwich,
  '🧾': Receipt,
  '📊': ChartNoAxesColumnIncreasing,
  '🛵': Bike,
  '💸': BadgePercent,
  '📱': Smartphone,
  '🧮': Calculator,
  '📈': ChartNoAxesColumnIncreasing,
  '📶': WifiOff,
  '🧩': Puzzle,
  '🏷️': Tag,
  '🙋': MessageSquare,
  '🔓': KeyRound,
  '🗺️': MapPinned,
  '📋': ClipboardList,
  '➗': Calculator,
  '🍷': Martini,
  '🔄': RefreshCw,
  '🍳': ChefHat,
  '💵': Banknote,
  '🔗': Link2,
  '👥': Users,
  '🎭': UserCog,
  '🔒': LockKeyhole,
  '✉️': Mail,
  '⏳': Hourglass,
  '❌': CircleX,
  '📵': Smartphone,
  '✗': X,
  '✓': Check,
  '✔': Check,
  '✕': X,
  '✂': Scissors,
  '🪑': Table2,
  '🍽️': Table2,
  '💳': CreditCard,
  '🔑': KeyRound,
  PC: Monitor,
  '✅': CircleCheckBig,
  '⚠️': TriangleAlert,
  '🎉': PartyPopper,
  '📄': FileText,
  '📗': Sheet,
  '🛒': ShoppingBag,
  '🔐': LockKeyhole,
  '🖨️': Printer,
  '🟠': Store,
  '🟣': Store,
  '🔴': Store,
  '🟡': Store,
  '🔵': Store,
  retirada: ShoppingBag,
  delivery: Bike,
  dinheiro: Banknote,
  cartao_debito: CreditCard,
  cartao_credito: CreditCard,
  pix: Smartphone,
  fiado: NotebookPen,
  plataformas: Store,
  balcao: Monitor,
  cozinha: ChefHat,
  add: Plus,
  remove: Minus,
  close: X,
  support: MessageSquare,
  smartphone: Smartphone,
  sparkles: Sparkles,
  package: Package,
  hands: HandCoins,
  access: ShieldCheck,
  mesas: Table2,
  printer: Printer,
  lanchonete: Sandwich,
  hamburgueria: Sandwich,
  deliveryProprio: Bike,
  mei: Smartphone,
  excel: Sheet,
  zelo: Zap,
  compareFail: CircleX,
  compareOk: CircleCheckBig,
  chat: MessageSquare,
  assistant: Sparkles,
  blog: BookOpen,
  moduleMesas: Armchair
};

export function resolveAppIcon(name, fallback = Sparkles) {
  return iconMap[name] || fallback;
}

export { iconMap };
