-- Fiado auditável: razão imutável, crédito de cliente e recebimento atômico.
--
-- Pré-rollout obrigatório: conferir no banco real a definição atualmente instalada de
-- criar_venda_completa(jsonb) e os tipos de caixas/caixa_movimentacoes. A CLI vinculada
-- recusou a consulta de leitura nesta sessão (403 da Management API), portanto esta
-- migration não deve ser aplicada sem essa verificação operacional.

begin;

create table if not exists public.fiado_lancamentos (
  id bigint generated by default as identity primary key,
  id_usuario uuid not null references auth.users(id) on delete cascade,
  id_pessoa uuid not null references public.pessoas(id) on delete restrict,
  id_venda bigint null references public.vendas(id) on delete set null,
  id_caixa integer null references public.caixas(id) on delete set null,
  id_operador uuid null references auth.users(id) on delete set null,
  natureza text not null check (natureza in ('saldo_inicial', 'debito_venda', 'pagamento', 'estorno_venda')),
  -- Valor assinado: positivo aumenta a dívida; negativo cria/consome crédito.
  valor numeric(12,2) not null check (valor <> 0),
  descricao text not null default '',
  idempotency_key text null,
  created_at timestamptz not null default now()
);

-- Referência da entrada de caixa criada junto com um recebimento.
-- Permite excluir um pagamento lançado por engano sem deixar o caixa divergente.
alter table public.fiado_lancamentos
  add column if not exists id_caixa_movimentacao integer null
  references public.caixa_movimentacoes(id) on delete set null;

create index if not exists fiado_lancamentos_pessoa_created_idx
  on public.fiado_lancamentos (id_pessoa, created_at desc, id desc);
create index if not exists fiado_lancamentos_usuario_created_idx
  on public.fiado_lancamentos (id_usuario, created_at desc);
create unique index if not exists fiado_lancamentos_idempotency_idx
  on public.fiado_lancamentos (id_usuario, idempotency_key)
  where idempotency_key is not null;

comment on table public.fiado_lancamentos is
  'Razão imutável do fiado. Valor positivo é débito; negativo é pagamento, crédito ou estorno.';

comment on table public.fiado_lancamentos is
  'Razao do fiado. Valor positivo e debito; negativo e pagamento, credito ou estorno. Recebimentos podem ser excluidos por RPC autorizada para corrigir erros de lancamento.';

alter table public.fiado_lancamentos enable row level security;
drop policy if exists fiado_lancamentos_select_owner on public.fiado_lancamentos;
create policy fiado_lancamentos_select_owner on public.fiado_lancamentos
  for select to authenticated
  using (id_usuario = public.get_owner_user_id(auth.uid()));

-- Escritas são exclusivamente por RPC/triggers SECURITY DEFINER; o browser só lê.
revoke all on public.fiado_lancamentos from public, anon, authenticated;
grant select on public.fiado_lancamentos to authenticated;
grant all on public.fiado_lancamentos to service_role;

-- Não há como reconstruir pagamentos legados com precisão. Preserva-se o saldo atual
-- em uma abertura única, e novos eventos passam a compor o extrato.
insert into public.fiado_lancamentos (id_usuario, id_pessoa, natureza, valor, descricao, idempotency_key, created_at)
select p.id_usuario,
       p.id,
       'saldo_inicial',
       coalesce(p.saldo_fiado, 0),
       'Saldo trazido da ficha anterior à implantação do extrato.',
       'saldo-inicial:' || p.id,
       now()
from public.pessoas p
where coalesce(p.saldo_fiado, 0) <> 0
on conflict (id_usuario, idempotency_key) where idempotency_key is not null do nothing;

create or replace function public.fiado_registrar_debito_venda()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_valor numeric(12,2);
begin
  if new.forma_pagamento <> 'fiado' or new.id_cliente is null then
    return new;
  end if;
  v_valor := coalesce(new.valor_total, 0);

  if v_valor <= 0 then return new; end if;

  insert into public.fiado_lancamentos (
    id_usuario, id_pessoa, id_venda, id_caixa, id_operador,
    natureza, valor, descricao, idempotency_key, created_at
  ) values (
    new.id_usuario,
    new.id_cliente,
    new.id,
    new.id_caixa,
    null,
    'debito_venda',
    v_valor,
    'Compra fiado',
    'venda-fiado:' || new.id,
    coalesce(new.created_at, now())
  ) on conflict (id_usuario, idempotency_key) where idempotency_key is not null do nothing;

  return new;
end;
$$;

drop trigger if exists fiado_debito_venda_ledger on public.vendas;
create trigger fiado_debito_venda_ledger
  after insert on public.vendas
  for each row execute function public.fiado_registrar_debito_venda();

-- Para venda múltipla, a parcela fiado está em vendas_pagamentos.
-- O id_cliente já foi gravado na venda pela RPC canônica.
create or replace function public.fiado_registrar_debito_pagamento_venda()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_venda public.vendas%rowtype;
begin
  if new.forma_pagamento <> 'fiado' or coalesce(new.valor, 0) <= 0 then
    return new;
  end if;
  select * into v_venda from public.vendas where id = new.id_venda;
  if v_venda.id_cliente is null then
    raise exception 'Pagamento fiado exige cliente vinculado.' using errcode = '23514';
  end if;

  insert into public.fiado_lancamentos (
    id_usuario, id_pessoa, id_venda, id_caixa, natureza, valor, descricao, idempotency_key, created_at
  ) values (
    v_venda.id_usuario, v_venda.id_cliente, v_venda.id, v_venda.id_caixa,
    'debito_venda', new.valor, 'Parcela fiado da venda',
    'venda-pagamento-fiado:' || new.id, coalesce(v_venda.created_at, now())
  ) on conflict (id_usuario, idempotency_key) where idempotency_key is not null do nothing;
  return new;
end;
$$;

drop trigger if exists fiado_debito_venda_pagamento_ledger on public.vendas_pagamentos;
create trigger fiado_debito_venda_pagamento_ledger
  after insert on public.vendas_pagamentos
  for each row execute function public.fiado_registrar_debito_pagamento_venda();

create or replace function public.fiado_actor_can(p_permission text, p_owner uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select auth.uid() = p_owner
    or exists (
      select 1
      from public.access_users au
      join public.access_roles ar
        on ar.id = au.role_id and ar.owner_user_id = au.owner_user_id
      where au.auth_user_id = auth.uid()
        and au.owner_user_id = p_owner
        and au.status = 'active'
        and coalesce((ar.permissions ->> p_permission)::boolean, false)
    );
$$;

create or replace function public.fiado_registrar_pagamento_v2(
  p_id_pessoa uuid,
  p_valor numeric,
  p_adicionar_ao_caixa boolean default true,
  p_id_caixa integer default null,
  p_idempotency_key text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor uuid := auth.uid();
  v_owner uuid;
  v_pessoa public.pessoas%rowtype;
  v_caixa_id integer;
  v_caixa_movimentacao_id integer;
  v_saldo_anterior numeric(12,2);
  v_saldo_atual numeric(12,2);
  v_lancamento public.fiado_lancamentos%rowtype;
begin
  if v_actor is null then raise exception 'Não autenticado.' using errcode = '28000'; end if;
  if coalesce(p_valor, 0) <= 0 then raise exception 'Informe um valor maior que zero.' using errcode = '22023'; end if;
  v_owner := public.get_owner_user_id(v_actor);
  if not public.fiado_actor_can('fiado.receber', v_owner) then
    raise exception 'Você não tem permissão para receber fiado.' using errcode = '42501';
  end if;

  if p_idempotency_key is not null then
    select * into v_lancamento from public.fiado_lancamentos
      where id_usuario = v_owner and idempotency_key = p_idempotency_key;
    if found then
      select coalesce(saldo_fiado, 0) into v_saldo_atual from public.pessoas where id = p_id_pessoa;
      return jsonb_build_object('idempotent', true, 'lancamento_id', v_lancamento.id, 'saldo_atual', v_saldo_atual);
    end if;
  end if;

  select * into v_pessoa from public.pessoas
    where id = p_id_pessoa and id_usuario = v_owner for update;
  if not found then raise exception 'Pessoa não encontrada.' using errcode = 'P0002'; end if;
  v_saldo_anterior := coalesce(v_pessoa.saldo_fiado, 0);

  if p_adicionar_ao_caixa then
    v_caixa_id := p_id_caixa;
    if v_caixa_id is null then
      select id into v_caixa_id from public.caixas
        where id_usuario = v_owner and data_fechamento is null
        order by data_abertura desc limit 1;
    end if;
    if v_caixa_id is null or not exists (
      select 1 from public.caixas where id = v_caixa_id and id_usuario = v_owner and data_fechamento is null
    ) then
      raise exception 'Abra um caixa para adicionar este recebimento à gaveta.' using errcode = 'P0001';
    end if;
    insert into public.caixa_movimentacoes (id_caixa, id_usuario, id_operador, tipo, valor, motivo)
      values (v_caixa_id, v_owner, v_actor, 'suprimento', p_valor, 'Pagamento fiado de ' || v_pessoa.nome)
      returning id into v_caixa_movimentacao_id;
  end if;

  update public.pessoas
    set saldo_fiado = v_saldo_anterior - p_valor
    where id = v_pessoa.id
    returning saldo_fiado into v_saldo_atual;

  insert into public.fiado_lancamentos (
    id_usuario, id_pessoa, id_caixa, id_caixa_movimentacao, id_operador, natureza, valor, descricao, idempotency_key
  ) values (
    v_owner, v_pessoa.id, v_caixa_id, v_caixa_movimentacao_id, v_actor, 'pagamento', -p_valor,
    'Pagamento recebido' || case when p_adicionar_ao_caixa then ' e adicionado ao caixa.' else '.' end,
    p_idempotency_key
  ) returning * into v_lancamento;

  return jsonb_build_object(
    'idempotent', false,
    'lancamento_id', v_lancamento.id,
    'saldo_anterior', v_saldo_anterior,
    'saldo_atual', v_saldo_atual,
    'credito_gerado', greatest(0, -v_saldo_atual)
  );
end;
$$;

create or replace function public.fiado_excluir_pagamento(p_id_lancamento bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor uuid := auth.uid();
  v_owner uuid;
  v_lancamento public.fiado_lancamentos%rowtype;
  v_pessoa public.pessoas%rowtype;
  v_saldo_anterior numeric(12,2);
  v_saldo_atual numeric(12,2);
  v_valor numeric(12,2);
begin
  if v_actor is null then
    raise exception 'Não autenticado.' using errcode = '28000';
  end if;

  v_owner := public.get_owner_user_id(v_actor);
  if not public.fiado_actor_can('fiado.receber', v_owner) then
    raise exception 'Você não tem permissão para excluir recebimentos de fiado.' using errcode = '42501';
  end if;

  -- Lock order: pessoa antes do lançamento, igual ao recebimento, para evitar corrida.
  select p.* into v_pessoa
    from public.pessoas p
    join public.fiado_lancamentos l on l.id_pessoa = p.id
   where l.id = p_id_lancamento
     and l.id_usuario = v_owner
     and l.natureza = 'pagamento'
     and p.id_usuario = v_owner
   for update of p;
  if not found then
    raise exception 'Pagamento recebido não encontrado.' using errcode = 'P0002';
  end if;

  select * into v_lancamento
    from public.fiado_lancamentos
   where id = p_id_lancamento
     and id_usuario = v_owner
     and id_pessoa = v_pessoa.id
     and natureza = 'pagamento'
   for update;
  if not found then
    raise exception 'Pagamento recebido não encontrado.' using errcode = 'P0002';
  end if;

  v_valor := abs(v_lancamento.valor);
  if v_valor <= 0 then
    raise exception 'O pagamento não possui um valor válido.' using errcode = '22023';
  end if;
  v_saldo_anterior := coalesce(v_pessoa.saldo_fiado, 0);

  if v_lancamento.id_caixa_movimentacao is not null then
    delete from public.caixa_movimentacoes
     where id = v_lancamento.id_caixa_movimentacao
       and id_caixa = v_lancamento.id_caixa
       and id_usuario = v_owner;
  elsif v_lancamento.id_caixa is not null and v_lancamento.descricao like '%adicionado ao caixa%' then
    raise exception 'Este pagamento não tem a movimentação de caixa vinculada. Atualize o fichário ou faça o ajuste no caixa.' using errcode = 'P0001';
  end if;

  update public.pessoas
     set saldo_fiado = v_saldo_anterior + v_valor
   where id = v_pessoa.id
     and id_usuario = v_owner
   returning saldo_fiado into v_saldo_atual;

  delete from public.fiado_lancamentos
   where id = v_lancamento.id
     and id_usuario = v_owner;

  return jsonb_build_object(
    'excluido', true,
    'lancamento_id', v_lancamento.id,
    'valor_excluido', v_valor,
    'saldo_anterior', v_saldo_anterior,
    'saldo_atual', v_saldo_atual
  );
end;
$$;

create or replace function public.fiado_estornar_venda(p_id_venda bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor uuid := auth.uid();
  v_owner uuid;
  v_venda public.vendas%rowtype;
  v_valor numeric(12,2) := 0;
  v_saldo numeric(12,2);
begin
  if v_actor is null then raise exception 'Não autenticado.' using errcode = '28000'; end if;
  v_owner := public.get_owner_user_id(v_actor);
  select * into v_venda from public.vendas where id = p_id_venda and id_usuario = v_owner for update;
  if not found or v_venda.id_cliente is null then return jsonb_build_object('valor_estornado', 0); end if;
  if exists (select 1 from public.fiado_lancamentos where id_venda = p_id_venda and natureza = 'estorno_venda') then
    return jsonb_build_object('idempotent', true, 'valor_estornado', 0);
  end if;
  if v_venda.forma_pagamento = 'fiado' then
    v_valor := coalesce(v_venda.valor_total, 0);
  elsif v_venda.forma_pagamento = 'multiplo' then
    select coalesce(sum(valor), 0) into v_valor from public.vendas_pagamentos
      where id_venda = p_id_venda and forma_pagamento = 'fiado';
  end if;
  if v_valor <= 0 then return jsonb_build_object('valor_estornado', 0); end if;
  update public.pessoas set saldo_fiado = coalesce(saldo_fiado, 0) - v_valor
    where id = v_venda.id_cliente and id_usuario = v_owner
    returning saldo_fiado into v_saldo;
  insert into public.fiado_lancamentos (id_usuario, id_pessoa, id_venda, id_operador, natureza, valor, descricao, idempotency_key)
    values (v_owner, v_venda.id_cliente, p_id_venda, v_actor, 'estorno_venda', -v_valor,
      'Estorno da venda ' || coalesce(v_venda.numero_venda::text, p_id_venda::text), 'estorno-venda:' || p_id_venda);
  return jsonb_build_object('valor_estornado', v_valor, 'saldo_atual', v_saldo);
end;
$$;

revoke all on function public.fiado_registrar_pagamento_v2(uuid, numeric, boolean, integer, text) from public, anon;
grant execute on function public.fiado_registrar_pagamento_v2(uuid, numeric, boolean, integer, text) to authenticated, service_role;
revoke all on function public.fiado_estornar_venda(bigint) from public, anon;
grant execute on function public.fiado_estornar_venda(bigint) to authenticated, service_role;
revoke all on function public.fiado_excluir_pagamento(bigint) from public, anon;
grant execute on function public.fiado_excluir_pagamento(bigint) to authenticated, service_role;

commit;
