begin;
create temporary table manual_fixture(owner_id uuid,other_id uuid,operator_id uuid,role_id uuid,company_id uuid,grp uuid,opt uuid,op jsonb,result jsonb) on commit drop;
insert into manual_fixture values(gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),null,null);
grant select,update on manual_fixture to authenticated;
insert into auth.users(id,email,aud,role,raw_app_meta_data,raw_user_meta_data,created_at,updated_at)
 select id,'manual-'||id||'@invalid.local','authenticated','authenticated','{}','{}',now(),now()
 from manual_fixture f cross join lateral(values(f.owner_id),(f.other_id),(f.operator_id)) a(id);
insert into public.empresa_perfil(id,user_id,nome_exibicao) select company_id,owner_id,'Manual test' from manual_fixture;
insert into public.access_roles(id,owner_user_id,name,permissions) select role_id,owner_id,'Reader','{"pedidos.acessar":true}' from manual_fixture;
insert into public.access_users(owner_user_id,auth_user_id,email,role_id,status) select owner_id,operator_id,'manual-op@invalid.local',role_id,'active' from manual_fixture;
insert into public.produtos(id,id_usuario,nome,preco,controlar_estoque,estoque_atual) select 912801,owner_id,'Manual test',10,true,0 from manual_fixture;
insert into public.produtos(id,id_usuario,nome,preco) select 912802,other_id,'Other tenant',10 from manual_fixture;
insert into public.subscriptions(user_id,status,plan_tier,has_zelo_menu,current_period_end) select owner_id,'active','pdv',true,now()+interval '30 days' from manual_fixture;
create function pg_temp.manual_assert(condition boolean,message text) returns void language plpgsql as $$ begin if condition is distinct from true then raise exception 'MANUAL ASSERT: %',message; end if; end $$;
create function pg_temp.manual_op(op_id text,payload jsonb) returns jsonb language sql as $$
 select jsonb_build_object('operationId',op_id,'schemaVersion',1,'type','order.create','deviceId','manual-fixture','operatorId',auth.uid(),'ownerUserId',owner_id,'entityType','order','entityId',op_id,'sequence',1,'dependencies','[]'::jsonb,'occurredAt','2026-09-05T12:00:00Z','payload',payload) from manual_fixture
$$;
set local role authenticated;
select set_config('request.jwt.claims',jsonb_build_object('role','authenticated','sub',owner_id)::text,true) from manual_fixture;
select public.offline_bootstrap_v1('manual-fixture','enable');
update manual_fixture set op=pg_temp.manual_op('manual-empty-fields','{"items":[{"productId":912801,"quantity":2,"unitPrice":10}],"deliveryFee":3.5}');
update manual_fixture set result=public.apply_offline_operation_v1(op);
select pg_temp.manual_assert(result->>'status'='applied','optional fields accepted: '||result::text) from manual_fixture;
select pg_temp.manual_assert(public.apply_offline_operation_v1(op)->>'status'='already_applied','lost response is idempotent') from manual_fixture;
reset role;
select pg_temp.manual_assert((select total=23.5 and source='manual' and status='pending_review' and customer='{}' from public.zelo_orders where id=(f.result#>>'{result,id}')::uuid),'canonical total/status') from manual_fixture f;
select pg_temp.manual_assert((select count(*) from public.zelo_orders)=1,'one order');
select pg_temp.manual_assert((select estoque_atual from public.produtos where id=912801)=0,'creation does not reserve stock');
set local role authenticated;
update manual_fixture set result=public.apply_offline_operation_v1(pg_temp.manual_op('wrong-tenant','{"items":[{"productId":912802,"quantity":1,"unitPrice":10}]}'));
select pg_temp.manual_assert(result->>'status'='needs_review','cross-tenant product blocked') from manual_fixture;
update manual_fixture set result=public.apply_offline_operation_v1(pg_temp.manual_op('wrong-price','{"items":[{"productId":912801,"quantity":1,"unitPrice":1}]}'));
select pg_temp.manual_assert(result->>'status'='needs_review','changed price requires review') from manual_fixture;
update manual_fixture set result=public.apply_offline_operation_v1(pg_temp.manual_op('bad-fee','{"items":[{"productId":912801,"quantity":1,"unitPrice":10}],"deliveryFee":-1}'));
select pg_temp.manual_assert(result->>'status'='needs_review','negative freight blocked') from manual_fixture;
select set_config('request.jwt.claims',jsonb_build_object('role','authenticated','sub',operator_id)::text,true) from manual_fixture;
select pg_temp.manual_assert((public.offline_bootstrap_v1('orders-only-device','register')->>'registered')::boolean,'orders-only operator prepares device');
update manual_fixture set result=public.apply_offline_operation_v1(pg_temp.manual_op('reader-cannot-create','{"items":[{"productId":912801,"quantity":1,"unitPrice":10}]}'));
select pg_temp.manual_assert(result->>'status'='rejected','read-only operator blocked') from manual_fixture;
reset role;
insert into public.zelomenu_modifier_groups(id,id_usuario,id_produto,nome,min_selecoes,max_selecoes) select grp,owner_id,912801,'Adicional',1,1 from manual_fixture;
insert into public.zelomenu_modifier_options(id,id_usuario,id_grupo,nome,price_delta) select opt,owner_id,grp,'Extra',2 from manual_fixture;
set local role authenticated;
select set_config('request.jwt.claims',jsonb_build_object('role','authenticated','sub',owner_id)::text,true) from manual_fixture;
update manual_fixture set result=public.apply_offline_operation_v1(pg_temp.manual_op('missing-required','{"items":[{"productId":912801,"quantity":1,"unitPrice":10}]}'));
select pg_temp.manual_assert(result->>'status'='needs_review','required modifier enforced') from manual_fixture;
update manual_fixture set op=pg_temp.manual_op('assembled',jsonb_build_object('items',jsonb_build_array(jsonb_build_object('productId',912801,'quantity',2,'unitPrice',12,'modifiers',jsonb_build_array(jsonb_build_object('groupId',grp,'selectedOptions',jsonb_build_array(jsonb_build_object('optionId',opt,'quantity',1,'priceDelta',2))))))));
update manual_fixture set result=public.apply_offline_operation_v1(op);
select pg_temp.manual_assert(result->>'status'='applied','assembled canonical: '||result::text) from manual_fixture;
reset role;
select pg_temp.manual_assert((select total from public.zelo_orders where id=(f.result#>>'{result,id}')::uuid)=24,'modifiers included') from manual_fixture f;
-- A pizza captured offline remains tied to its historical, activated revision.
insert into public.produtos(id,id_usuario,nome,preco,controlar_estoque) select 912803,owner_id,'Pizza',0,false from manual_fixture;
alter table manual_fixture add column config jsonb;
set local role authenticated;
update manual_fixture set config=public.save_pizza_config(912803,null,'{"version":1,"pricingMode":"highest","sizes":[{"id":"large","name":"Grande","maxFlavors":2,"active":true}],"flavors":[{"id":"a","name":"Queijo","active":true,"prices":{"large":40}},{"id":"b","name":"Frango","active":true,"prices":{"large":60}}]}');
update manual_fixture set op=pg_temp.manual_op('pizza-historical',jsonb_build_object('items',jsonb_build_array(jsonb_build_object('productId',912803,'quantity',1,'unitPrice',60,'pizza',jsonb_build_object('revision',config->>'revision','sizeId','large','flavorIds',jsonb_build_array('a','b'))))));
update manual_fixture set config=public.save_pizza_config(912803,(config->>'revision')::uuid,jsonb_set(config,'{flavors,1,prices,large}','80'));
update manual_fixture set result=public.apply_offline_operation_v1(op);
select pg_temp.manual_assert(result->>'status'='applied','historical pizza: '||result::text) from manual_fixture;
select pg_temp.manual_assert(public.apply_offline_operation_v1(op)->>'status'='already_applied','historical pizza retry') from manual_fixture;
reset role;
select pg_temp.manual_assert((select total from public.zelo_orders where id=(f.result#>>'{result,id}')::uuid)=60,'historical price retained') from manual_fixture f;
select pg_temp.manual_assert((select pizza#>>'{flavors,0,denominator}' from public.zelo_order_items where order_id=(f.result#>>'{result,id}')::uuid)='2','pizza composition preserved') from manual_fixture f;
select pg_temp.manual_assert(not has_function_privilege('authenticated','offline_internal.create_manual_order(uuid,jsonb)','EXECUTE'),'private helper inaccessible');
update public.subscriptions set has_zelo_menu=false where user_id=(select owner_id from manual_fixture);
set local role authenticated;
update manual_fixture set result=public.apply_offline_operation_v1(pg_temp.manual_op('missing-addon','{"items":[{"productId":912801,"quantity":1,"unitPrice":10}]}'));
select pg_temp.manual_assert(result->>'status'='rejected','missing menu entitlement rejected') from manual_fixture;
rollback;
