import sys; sys.path.insert(0, '/home/user/zelopdv/docs/design-system/mockups')
from _mk import fonts, i, money, sidebar, CSS, ICON, MOTION_CSS, MOTION_JS
ICON.update({
 'down':'<path d="M6 9l6 6 6-6"/>','upload':'<path d="M12 16V4M7 9l5-5 5 5"/><path d="M4 16v4h16v-4"/>','lock':'<rect x="5" y="11" width="14" height="9" rx="2"/><path d="M8 11V8a4 4 0 0 1 8 0v3"/>',
 'check':'<path d="m5 12 5 5 9-10"/>','card':'<rect x="3" y="6" width="18" height="13" rx="2"/><path d="M3 10h18M7 15h4"/>','pix':'<path d="M12 3l9 9-9 9-9-9z"/><path d="M8 12l4-4 4 4-4 4z"/>',
 'hour':'<path d="M7 3h10M7 21h10M8 3c0 5 8 5 8 9s-8 4-8 9M16 3c0 5-8 5-8 9"/>','ext':'<path d="M14 4h6v6M20 4l-9 9"/><path d="M18 14v6H4V6h6"/>','copy':'<rect x="8" y="8" width="12" height="12" rx="2"/><path d="M4 16V4h12"/>',
 'printer':'<path d="M7 9V3h10v6"/><rect x="3" y="9" width="18" height="8" rx="2"/><path d="M7 14h10v7H7z"/>','wifi':'<path d="M2 9a15 15 0 0 1 20 0M5 12.5a10 10 0 0 1 14 0M8.5 16a5 5 0 0 1 7 0"/><path d="M12 19.5h.01"/>',
 'calc':'<rect x="5" y="3" width="14" height="18" rx="2"/><path d="M8 7h8M8 11h.01M12 11h.01M16 11h.01M8 15h.01M12 15h.01M16 15h.01"/>','menu':'<path d="M9 5H7a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V7a2 2 0 0 0-2-2h-2"/><path d="M9 5a2 2 0 0 0 2 2h2a2 2 0 0 0 2-2 2 2 0 0 0-2-2h-2a2 2 0 0 0-2 2z"/>',
 'target':'<circle cx="12" cy="12" r="8"/><circle cx="12" cy="12" r="4"/><path d="M12 12h.01"/>','arrow':'<path d="M5 12h14M13 6l6 6-6 6"/>','alert':'<path d="M12 4 2.5 20h19L12 4Z"/><path d="M12 10v4M12 17h.01"/>',
})
def num(v, dec=2): return f'<span class="cnt" data-to="{v}" data-dec="{dec}">{f"{v:,.{dec}f}".replace(",","X").replace(".",",").replace("X",".")}</span>'
def morph(label, cls='btn pri'): return f'<button class="{cls} morph-lite">{label}</button>'
def sw(on=True): return f'<button class="sw2 {"on" if on else ""}" role="switch" aria-checked="{"true" if on else "false"}"><i></i></button>'
def field(lbl, val, req=False, mono=False, help=''):
    return f'<label class="fld"><span class="lbl">{lbl}{" <b>*</b>" if req else ""}</span><span class="inp{" mono" if mono else ""}">{val}</span>{f"<small>{help}</small>" if help else ""}</label>'

# ── Perfil: 5 abas ──
T_PERFIL=f'''<div class="pane" data-t="perfil"><section class="card pad"><p class="eyebrow">Logotipo</p><div class="logo-row"><div class="logo-ph">PB</div><div><p class="b">Logo no recibo e no cardápio</p><p class="cap">PNG ou JPG, até 1 MB. Fica em preto e branco na térmica.</p></div><button class="btn out">{i("upload")}Enviar logo</button></div></section>
<section class="card pad"><p class="eyebrow">Dados básicos</p><div class="g2f">{field("Nome exibido no recibo","Padaria Bom Dia",True)}{field("E-mail","ana@padariabomdia.com.br",help="O e-mail de login não muda por aqui.")}</div></section>
<section class="card pad row-between"><div><p class="eyebrow">Segurança</p><p class="b">Senha</p><p class="cap">Defina uma nova senha para sua conta agora.</p></div><button class="btn out">{i("lock")}Redefinir senha</button></section></div>'''
T_EMPRESA=f'''<div class="pane" data-t="empresa" hidden><section class="card pad"><p class="eyebrow">Informações fiscais</p><div class="g2f">{field("Nome fantasia","Padaria Bom Dia",True)}{field("Razão social","Bom Dia Panificadora Ltda")}{field("CNPJ / CPF","12.345.678/0001-90",True,True)}{field("Inscrição estadual","123.456.789.110",mono=True)}</div></section>
<section class="card pad"><p class="eyebrow">Contato e endereço</p><div class="g2f">{field("Telefone da loja","(11) 3333-4444",True,True)}{field("Endereço completo","Rua das Acácias, 120 · Jardim América")}</div>{field("Mensagem de rodapé do recibo","Obrigado pela preferência! Volte sempre.")}</section></div>'''
T_ASSIN=f'''<div class="pane" data-t="assinatura" hidden><section class="card pad plan-now"><div><p class="eyebrow">Seu plano</p><p class="pn-t">Pacote Gestão + Atendimento</p><p class="cap">ZeloPDV + ZeloChat + ZeloMenu · Módulo Mesas</p></div><div class="r"><span class="money lg"><small>R$</small>{num(228)}</span><p class="cap">por mês · renova em 12/10/2026</p></div>
<div class="plan-acts"><a class="btn pri" href="#assin">Gerenciar assinatura</a><button class="btn out">{i("ext")}Gerenciar pagamentos</button></div></section>
<section class="card tbl"><div class="card-t pad-x"><p class="eyebrow">Histórico de faturas</p></div><table><thead><tr><th>Data</th><th>Descrição</th><th>Forma</th><th class="r">Valor</th><th></th></tr></thead><tbody>
{"".join(f'<tr><td class="mono">{d}</td><td>{x}</td><td><span class="tag">{f}</span></td><td class="r">{money(v,"sm")}</td><td class="r"><span class="stp ok">{i("check",14)}Pago</span></td></tr>' for d,x,f,v in [("12/09/2026","Pacote Gestão + Atendimento + Mesas","Pix",228),("12/08/2026","Pacote Gestão + Atendimento + Mesas","Pix",228),("12/07/2026","Pacote Gestão + Atendimento","Cartão",198)])}</tbody></table></section></div>'''
PLATS=[("iFood","12,5",True),("Rappi","15,0",False),("99Food","10,0",False),("Aiqfome","9,0",False)]
T_PREF=f'''<div class="pane" data-t="preferencias" hidden><section class="card pad"><p class="eyebrow">Impressão</p><div class="g2f"><label class="fld"><span class="lbl">Tipo de impressora</span><span class="inp sel">Térmica 80 mm — padrão{i("down",16)}</span></label></div></section>
<section class="card pad"><div class="row-between"><div><p class="eyebrow">Plataformas de venda</p><p class="cap">Comissão de cada plataforma, usada em Relatórios → Custos de plataforma.</p></div></div><ul class="plist">{"".join(f'<li><span class="b">{n}</span><span class="pct"><span class="inp mono sm">{p}</span>%</span>{sw(on)}</li>' for n,p,on in PLATS)}</ul></section>
<section class="card pad"><div class="row-between"><div><p class="eyebrow">Tabelas de preço</p><p class="cap">Até 3 preços por produto (balcão, delivery, atacado).</p></div>{sw(True)}</div><div class="g3f">{field("Nome tabela 1","Balcão")}{field("Nome tabela 2","Delivery")}{field("Nome tabela 3","Atacado")}</div></section>
<section class="card pad"><p class="eyebrow">Notificações</p><ul class="nlist"><li><div><p class="b">Alerta de estoque baixo</p><p class="cap">Avisa quando um produto atinge o nível crítico.</p></div>{sw(True)}</li><li><div><p class="b">Lembrete de fechamento de caixa</p><p class="cap">Notifica ao final do dia se o caixa ainda está aberto.</p></div>{sw(False)}</li></ul></section></div>'''
T_INT=f'''<div class="pane" data-t="integracoes" hidden><section class="card pad row-between"><div class="ic-row"><span class="ic-b">{i("wifi")}</span><div><p class="b">Operação offline</p><p class="cap">Vendas sem internet ficam no aparelho e sobem quando a conexão volta.</p></div></div><span class="stp ok">{i("check",14)}Ativa neste aparelho</span></section>
<section class="card pad"><div class="row-between"><div class="ic-row"><span class="ic-b">{i("printer")}</span><div><p class="b">Zelo Impressão</p><p class="cap">Imprime cupons direto na térmica, sem janela do navegador.</p></div></div><span class="stp ok"><i class="dot"></i>Conectado</span></div>
<div class="g2f top"><label class="fld"><span class="lbl">Impressora</span><span class="inp sel">EPSON TM-T20X{i("down",16)}</span></label><div class="fld end">{morph(f'{i("printer")}Imprimir teste', 'btn out')}</div></div>
<p class="cap foot">Versão 1.4.2 · Não instalado em outro computador? <a class="lnk" href="#">Baixar o Zelo Impressão</a></p></section></div>'''
TABS_P=[("perfil","Perfil"),("empresa","Empresa"),("assinatura","Assinatura"),("preferencias","Preferências"),("integracoes","Integrações")]
DANGER=f'''<details class="danger"><summary>{i("alert",16)}Zona de perigo</summary><div class="row-between"><div><p class="b">Apagar conta</p><p class="cap">Agenda a exclusão com 30 dias de carência. Você pode reativar nesse prazo.</p></div><button class="btn danger">Apagar conta</button></div></details>'''
PERFIL_D=f'''<div class="frame d tall"><div class="app">{sidebar('Perfil')}<main class="main scroll">
<header class="ph"><div><p class="eyebrow">Conta / Meu perfil</p><h1 class="title">Configurações da conta</h1></div>{morph(f'{i("check")}Salvar alterações')}</header>
<div class="tabs ptabs">{"".join(f'<button class="{"on" if k=="perfil" else ""}" data-go="{k}">{n}</button>' for k,n in TABS_P)}</div>
<div class="panes narrow">{T_PERFIL}{T_EMPRESA}{T_ASSIN}{T_PREF}{T_INT}</div>{DANGER}</main></div></div>'''

# ── Assinatura: 3 etapas ──
PL=[("pdv","Para vender e controlar","ZeloPDV",59,"","PDV simples + estoque + financeiro"),("bundle","Tudo em um","Pacote Gestão + Atendimento",198,"Economize R$ 10","ZeloPDV + ZeloChat (IA no WhatsApp) + ZeloMenu"),("chat","Para atender no WhatsApp","ZeloChat",149,"","Atendimento WhatsApp com IA + cardápio online")]
PLANS_H=''.join(f'''<button class="plan{" sel" if k=="bundle" else ""}" data-price="{p}">{'<span class="pop">Mais popular</span>' if k=="bundle" else ""}<span class="eyebrow">{e}</span><span class="pl-n">{n}</span><span class="money lg"><small>R$</small>{p}<em>/mês</em></span>{f'<span class="save">{s}</span>' if s else ""}<span class="cap">{t}</span><span class="pl-cta">{"Plano atual" if k=="bundle" else "Escolher pacote"}</span></button>''' for k,e,n,p,s,t in PL)
ADD=[("Módulo Mesas",30,"Mesas, comandas e divisão de conta sem confusão no caixa.","Evita conta perdida, fechamento demorado e atendimento travado nas mesas.",True,""),("ZeloMenu",40,"Cardápio online com publicação no menu digital do seu negócio.","",False,"Já incluso no Pacote Gestão + Atendimento — você não perde este módulo."),("Controle de Acessos",30,"Equipe com permissões certas, sem senha compartilhada.","Evita acessos indevidos, alterações sem rastreio e bagunça operacional.",False,"")]
ADD_H=''.join(f'''<button class="addon{" sel" if on else ""}{" inc" if inc else ""}" data-price="{p}"{" disabled" if inc else ""}><span class="ad-top"><span class="b">{n}</span><span class="pill{" on" if on or inc else ""}">{"Já incluso" if inc else ("Selecionado" if on else "Opcional")}</span></span><span class="cap">{inc or t}</span>{f'<span class="pain">Resolve: {pn}</span>' if pn and not inc else ""}<span class="money sm">{"" if inc else f"<small>+R$</small>{p}/mês"}</span></button>''' for n,p,t,pn,on,inc in ADD)
STEP1=f'<div class="step" data-s="1"><p class="eyebrow">Mudar ou renovar</p><h2 class="h2">Escolha o pacote base da sua operação</h2><div class="plans">{PLANS_H}</div></div>'
STEP2=f'<div class="step" data-s="2" hidden><p class="eyebrow">Mudar ou renovar</p><h2 class="h2">Adicione só o que faz diferença</h2><div class="addons">{ADD_H}</div></div>'
STEP3=f'''<div class="step" data-s="3" hidden><p class="eyebrow">Mudar ou renovar</p><h2 class="h2">Revise e escolha como pagar</h2>
<div class="renew"><span>Vencimento atual <b class="mono">12/10/2026</b></span><span>Após o pagamento <b class="mono">12/11/2026</b></span></div>
<label class="fld doc"><span class="lbl">CPF ou CNPJ</span><span class="inp mono">000.000.000-00</span><small>O Pix precisa do documento de quem recebe. Fica salvo no seu perfil, você digita uma vez só. (aparece só se faltar)</small></label>
<div class="pays"><button class="pay" data-pix>{i("pix",22)}<span class="eyebrow">Pix</span><span class="b">Pagar com Pix agora</span><span class="cap">QR Code na hora, liberação automática ao confirmar.</span><span class="pl-cta">Gerar Pix</span></button><button class="pay">{i("card",22)}<span class="eyebrow">Cartão</span><span class="b">Assinar no cartão</span><span class="cap">Cobrança mensal automática pela Stripe.</span><span class="pl-cta">Ir para o pagamento</span></button></div></div>'''
SUMMARY=f'''<aside class="sum card pad"><p class="eyebrow">Renovação do pacote atual</p><p class="pn-t">Pacote Gestão + Atendimento</p><p class="cap">+ Módulo Mesas</p><div class="sum-t"><span class="cap">Total mensal</span><span class="money xl"><small>R$</small><span id="tot">228,00</span></span></div><div class="sum-acts"><button class="btn out" data-back>Voltar</button><button class="btn pri" data-next>Continuar</button></div></aside>'''
ASSIN_D=f'''<div class="frame d tall" id="assin"><div class="app">{sidebar('Perfil')}<main class="main scroll">
<header class="ph"><div><p class="eyebrow">Conta / Assinatura</p><h1 class="title">Sua assinatura Zelo</h1><p class="cap">Escolha o pacote, ajuste os módulos e finalize com Pix ou cartão em poucos passos.</p></div><a class="btn out" href="#">Entrar no sistema{i("arrow",16)}</a></header>
<div class="status ok">{i("check",20)}<div><p class="b">Assinatura ativa — Pacote Gestão + Atendimento</p><p class="cap">Próxima renovação: 12/10/2026 · R$ 228/mês</p></div></div>
<div class="status warn alt">{i("hour",20)}<div><p class="b">Teste termina em 5 dias</p><p class="cap">Válido até 01/10/2026. (variação durante o teste grátis)</p></div></div>
<div class="tabs steps">{"".join(f'<button class="{"on" if k==1 else ""}" data-step="{k}"><span class="sn">{k}</span>{n}</button>' for k,n in [(1,"Pacote"),(2,"Extensões"),(3,"Pagamento")])}</div>
<div class="wiz"><div class="steps-v">{STEP1}{STEP2}{STEP3}</div>{SUMMARY}</div>
<div class="cancel"><button class="btn danger">Cancelar assinatura</button><span class="cap">O acesso segue até o fim do período pago.</span></div></main></div></div>'''
QR=''.join(f'<i style="grid-area:{r+1}/{c+1}"></i>' for r in range(21) for c in range(21) if ((r*7+c*13+r*c)%5<2) or (r<7 and c<7) or (r<7 and c>13) or (r>13 and c<7))
PIX=f'''<div class="frame d pixf"><div class="scrim"></div><div class="pixs"><button class="x" aria-label="Fechar">×</button><div class="pix-h"><span class="ic-b">{i("pix",22)}</span><div><p class="eyebrow">Pagamento Pix</p><p class="h2">Aguardando pagamento</p><p class="cap">Valor: <span class="mono">R$ 228,00</span>/mês</p></div></div>
<div class="wait"><span class="spin"></span>Aguardando confirmação do pagamento…</div><div class="count"><span class="cap">QR Code válido por</span><b class="mono" id="cd">14:32</b><small class="cap">Quando vencer, um novo Pix é gerado automaticamente.</small></div>
<div class="qr">{QR}</div><label class="fld"><span class="lbl">Copia e cola</span><span class="inp mono code">00020126580014BR.GOV.BCB.PIX0136a1b2c3d4-e5f6-7890-abcd-ef1234567890520400005303986540522 8.005802BR5913ZELO PDV LTDA6009SAO PAULO62070503***6304ABCD</span></label>
<div class="pix-acts">{morph(f'{i("copy")}Copiar código Pix')}<button class="btn out morph-lite">Já paguei</button></div><p class="cap">Esta tela acompanha o pagamento automaticamente. Você pode fechar e voltar depois; o acesso é liberado quando o Pix for confirmado.</p></div></div>'''
TOOLS=[("calc","Precificação","Cadastre custo e preço de venda e acompanhe CMV e margem de cada produto do seu catálogo.","Grátis",True),("menu","Cardápio digital","Monte e compartilhe o cardápio online do seu negócio com link público.","Incluso",True),("target","Metas de venda","Defina metas de faturamento e acompanhe o progresso do mês em tempo real.","Em breve",False)]
FERR_D=f'''<div class="frame d"><div class="app">{sidebar('Ferramentas')}<main class="main">
<header class="ph"><div><p class="eyebrow">Outros / Ferramentas</p><h1 class="title">Ferramentas</h1><p class="cap">Recursos extras para você precificar, divulgar e organizar o seu negócio.</p></div></header>
<div class="tools">{"".join(f'<a class="tool{"" if av else " off"}" href="#"><span class="tl-top"><span class="ic-b">{i(ic,22)}</span><span class="tag{" ok" if tg=="Grátis" else ""}">{tg}</span></span><span class="pl-n">{t}</span><span class="cap">{d}</span>{f"<span class=pl-cta>Abrir{i(chr(97)+chr(114)+chr(114)+chr(111)+chr(119),16)}</span>" if av else "<span class=pl-cta>Em breve</span>"}</a>' for ic,t,d,tg,av in TOOLS)}</div>
<p class="cap note">Precificação e Cardápio digital seguem os padrões já aprovados: tabela em cartão, busca, valores em Mono, interruptores com mola.</p></main></div></div>'''
MOB_P=f'''<div class="frame m"><div class="mh"><div><p class="mh-t">Minha conta</p><p class="mh-s">Padaria Bom Dia</p></div></div><div class="m-body scroll">
<div class="tabs ptabs sm">{"".join(f'<button class="{"on" if k=="perfil" else ""}">{n}</button>' for k,n in TABS_P)}</div>
<section class="card pad"><p class="eyebrow">Logotipo</p><div class="logo-row m"><div class="logo-ph">PB</div><button class="btn out">{i("upload")}Enviar logo</button></div></section>
<section class="card pad">{field("Nome exibido no recibo","Padaria Bom Dia",True)}{field("E-mail","ana@padariabomdia.com.br")}</section>
<div class="sticky-save">{morph(f'{i("check")}Salvar alterações','btn pri wide')}</div></div>
<nav class="bn"><a>{i('bag')}PDV</a><a>{i('grid')}Gestão</a><a>{i('wallet')}Financeiro</a><a>{i('dots')}Outros</a><a class="on">{i('user')}Perfil</a></nav></div>'''
MOB_A=f'''<div class="frame m"><div class="mh"><div><p class="mh-t">Assinatura</p><p class="mh-s">Etapa 1 de 3 · Pacote</p></div></div><div class="m-body scroll">
<div class="status ok">{i("check",18)}<div><p class="b">Assinatura ativa</p><p class="cap">Renova em 12/10/2026</p></div></div>
<div class="dots"><i class="on"></i><i></i><i></i></div><div class="plans m">{PLANS_H}</div></div>
<div class="msum"><div><span class="cap">Pacote Gestão + Atendimento</span><span class="money md"><small>R$</small>228,00<em>/mês</em></span></div><button class="btn pri">Continuar</button></div>
<nav class="bn"><a>{i('bag')}PDV</a><a>{i('grid')}Gestão</a><a>{i('wallet')}Financeiro</a><a>{i('dots')}Outros</a><a class="on">{i('user')}Perfil</a></nav></div>'''

BN=lambda on: '<nav class="bn">'+''.join(f'<a class="{"on" if n==on else ""}">{i(ic)}{n}</a>' for ic,n in [('bag','PDV'),('grid','Gestão'),('wallet','Financeiro'),('dots','Outros'),('user','Perfil')])+'</nav>'
def mf(title, sub, body, on='Perfil', extra=''):
    return f'<div class="frame m"><div class="mh"><div><p class="mh-t">{title}</p><p class="mh-s">{sub}</p></div></div><div class="m-body scroll">{body}</div>{extra}{BN(on)}</div>'
def mtabs(active): return '<div class="tabs ptabs sm">'+''.join(f'<button class="{"on" if k==active else ""}">{n}</button>' for k,n in TABS_P)+'</div>'
SAVE=morph(f'{i("check")}Salvar alterações','btn pri wide')
M_EMP=mf('Minha conta','Empresa',mtabs('empresa')+'<section class="card pad"><p class="eyebrow">Informações fiscais</p>'+field("Nome fantasia","Padaria Bom Dia",True)+field("Razão social","Bom Dia Panificadora Ltda")+field("CNPJ / CPF","12.345.678/0001-90",True,True)+field("Inscrição estadual","123.456.789.110",mono=True)+'</section><section class="card pad"><p class="eyebrow">Contato e endereço</p>'+field("Telefone da loja","(11) 3333-4444",True,True)+field("Endereço completo","Rua das Acácias, 120")+'</section><div class="sticky-save">'+SAVE+'</div>')
INV=''.join(f'<li><div><p class="b mono">{d}</p><p class="cap">{f} · Pago</p></div>{money(v,"sm")}</li>' for d,f,v in [("12/09/2026","Pix",228),("12/08/2026","Pix",228),("12/07/2026","Cartão",198)])
M_ASS=mf('Minha conta','Assinatura',mtabs('assinatura')+'<section class="card pad plan-now m"><p class="eyebrow">Seu plano</p><p class="pn-t">Pacote Gestão + Atendimento</p><p class="cap">+ Módulo Mesas</p><div class="mrow"><span class="money"><small>R$</small>'+num(228)+'</span><span class="cap">/mês · renova 12/10</span></div><div class="mstack"><a class="btn pri wide" href="#">Gerenciar assinatura</a><button class="btn out wide">'+i("ext")+'Gerenciar pagamentos</button></div></section><section class="card"><p class="eyebrow pad-x">Histórico de faturas</p><ul class="inv">'+INV+'</ul></section>')
PL3=''.join(f'<li><span class="b">{n}</span><span class="pct"><span class="inp mono sm">{p}</span>%</span>{sw(on)}</li>' for n,p,on in PLATS[:3])
M_PREF=mf('Minha conta','Preferências',mtabs('preferencias')+'<section class="card pad"><p class="eyebrow">Impressão</p><label class="fld"><span class="lbl">Tipo de impressora</span><span class="inp sel">Térmica 80 mm'+i("down",16)+'</span></label></section><section class="card pad"><p class="eyebrow">Plataformas de venda</p><ul class="plist">'+PL3+'</ul></section><section class="card pad"><p class="eyebrow">Notificações</p><ul class="nlist"><li><div><p class="b">Estoque baixo</p><p class="cap">Avisa no nível crítico.</p></div>'+sw(True)+'</li><li><div><p class="b">Fechar o caixa</p><p class="cap">Lembrete no fim do dia.</p></div>'+sw(False)+'</li></ul></section>')
M_INT=mf('Minha conta','Integrações',mtabs('integracoes')+'<section class="card pad"><div class="ic-row"><span class="ic-b">'+i("wifi")+'</span><div><p class="b">Operação offline</p><p class="cap">Vendas sem internet sobem quando a conexão volta.</p></div></div><span class="stp ok mtop">'+i("check",14)+'Ativa neste aparelho</span></section><section class="card pad"><div class="ic-row"><span class="ic-b">'+i("printer")+'</span><div><p class="b">Zelo Impressão</p><p class="cap">Estado igual ao de hoje (não instalado / precisa de ajuda / conectado).</p></div></div><span class="stp mtop">Não instalado neste aparelho</span></section><details class="danger m" open><summary>'+i("alert",16)+'Zona de perigo</summary><p class="cap">Apagar conta agenda a exclusão com 30 dias de carência.</p><button class="btn danger wide">Apagar conta</button></details>')
M_STEP2=mf('Assinatura','Etapa 2 de 3 · Extensões','<div class="dots"><i></i><i class="on"></i><i></i></div><p class="h2 m">Adicione só o que faz diferença</p><div class="addons m">'+ADD_H+'</div>','Perfil','<div class="msum"><div><span class="cap">Pacote + Mesas</span><span class="money md"><small>R$</small>228,00<em>/mês</em></span></div><button class="btn pri">Revisar e pagar</button></div>')
M_STEP3=mf('Assinatura','Etapa 3 de 3 · Pagamento','<div class="dots"><i></i><i></i><i class="on"></i></div><section class="card pad tot-m"><p class="eyebrow">Pacote atual</p><span class="money xl"><small>R$</small>228,00</span><p class="cap">Pacote Gestão + Atendimento + Módulo Mesas</p></section><div class="renew m"><span>Vence <b class="mono">12/10</b></span><span>Após pagar <b class="mono">12/11</b></span></div><label class="fld"><span class="lbl">CPF ou CNPJ</span><span class="inp mono">000.000.000-00</span><small>Só aparece se faltar. Fica salvo no perfil.</small></label><div class="pays m"><button class="pay">'+i("pix",22)+'<span class="b">Pagar com Pix agora</span><span class="cap">Liberação automática ao confirmar.</span></button><button class="pay">'+i("card",22)+'<span class="b">Assinar no cartão</span><span class="cap">Cobrança mensal pela Stripe.</span></button></div><button class="btn out wide">Voltar</button>')
M_PIX='<div class="frame m pixm"><div class="mh"><div><p class="mh-t">Assinatura</p><p class="mh-s">Pagamento</p></div></div><div class="m-body"></div><div class="scrim"></div><div class="bsheet"><span class="grab"></span><div class="pix-h"><span class="ic-b">'+i("pix",22)+'</span><div><p class="eyebrow">Pagamento Pix</p><p class="h2 m">Aguardando pagamento</p></div></div><div class="count"><span class="cap">QR válido por</span><b class="mono">14:32</b></div><div class="qr sm">'+QR+'</div>'+morph(f'{i("copy")}Copiar código Pix','btn pri wide')+'<button class="btn out wide">Já paguei</button><div class="wait"><span class="spin"></span>Liberamos assim que o Pix confirmar.</div></div>'+BN("Perfil")+'</div>'
TL=''.join(f'<a class="tool{"" if av else " off"}" href="#"><span class="tl-top"><span class="ic-b">{i(ic,22)}</span><span class="tag{" ok" if tg=="Grátis" else ""}">{tg}</span></span><span class="pl-n">{t}</span><span class="cap">{d}</span></a>' for ic,t,d,tg,av in TOOLS)
M_FERR=mf('Ferramentas','Outros','<div class="tools m">'+TL+'</div>','Outros')
M_SUB=mf('Minha conta','Beto · Operador','<section class="card pad"><p class="eyebrow">Seus dados</p>'+field("Nome","Beto")+field("E-mail","beto@padariabomdia.com.br")+'<p class="cap mtop">Cargo: Operador de caixa. A assinatura é do titular da loja.</p></section><section class="card pad"><div class="ic-row"><span class="ic-b">'+i("wifi")+'</span><div><p class="b">Operação offline</p><p class="cap">Vendas sem internet ficam neste aparelho até a conexão voltar.</p></div></div><span class="stp ok mtop">'+i("check",14)+'Ativa</span></section><button class="btn out wide">'+i("lock")+'Redefinir senha</button>')
EXTRA='''
.frame.tall{height:auto}.frame.tall .app{min-height:900px}.main.scroll{overflow:visible;display:flex;flex-direction:column;gap:16px}
.btn.pri{background:var(--navy);color:#fff;border:0}.btn.danger{background:var(--white);border:1px solid var(--line);color:var(--err)}.btn.danger:hover{border-color:var(--err)}.btn.wide{width:100%;justify-content:center;height:52px}
.card{background:var(--white);border:1px solid var(--line);border-radius:14px}.pad{padding:18px 20px}.pad-x{padding:16px 20px 10px}.card-t{display:flex;justify-content:space-between}
.b{font:500 15px var(--ui);color:var(--ink);margin:0}.cap{margin:2px 0 0}.mono{font-family:var(--num)!important}.r{text-align:right}
.row-between{display:flex;justify-content:space-between;align-items:center;gap:16px}
.ptabs{margin-top:-4px}.panes{display:flex;flex-direction:column}.panes.narrow{max-width:860px}.pane{display:flex;flex-direction:column;gap:14px}.pane[hidden]{display:none}
.eyebrow+.g2f,.eyebrow+.fld,.eyebrow+.logo-row{margin-top:12px}
.g2f{display:grid;grid-template-columns:1fr 1fr;gap:14px}.g3f{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-top:14px}.g2f.top{margin-top:16px}
.fld{display:flex;flex-direction:column;gap:6px;margin-top:10px}.g2f .fld,.g3f .fld{margin-top:0}.fld .lbl{font:500 13px var(--ui);color:var(--label)}.fld .lbl b{color:var(--err);font-weight:500}.fld small{font:400 12px var(--ui);color:var(--muted)}.fld.end{justify-content:flex-end}
.inp{display:flex;align-items:center;justify-content:space-between;height:44px;padding:0 12px;border:1px solid var(--line);border-radius:12px;background:var(--white);font:400 15px var(--ui);color:var(--ink)}.inp.sm{height:36px;width:72px;justify-content:flex-end}.inp.code{height:auto;padding:10px 12px;font-size:12px;word-break:break-all;line-height:1.5;background:var(--sunk)}
.logo-row{display:flex;align-items:center;gap:16px}.logo-row>div:nth-child(2){flex:1}.logo-row.m{justify-content:space-between}.logo-ph{width:64px;height:64px;border-radius:14px;background:var(--sunk);display:grid;place-items:center;font:600 20px var(--num);color:var(--label);border:1px dashed var(--line2)}
.plan-now{display:grid;grid-template-columns:1fr auto;gap:10px 20px;align-items:end}.pn-t{font:600 20px/1.2 var(--num);letter-spacing:-.02em;margin:6px 0 0;color:var(--ink)}.plan-acts{grid-column:1/-1;display:flex;gap:8px;margin-top:6px}
.tag{padding:3px 8px;border-radius:7px;background:var(--sunk);font:500 12px var(--ui)}.tag.ok{background:var(--okbg);color:var(--ok)}
.stp{display:inline-flex;align-items:center;gap:6px;height:26px;padding:0 10px;border-radius:999px;font:500 12.5px var(--ui)}.stp.ok{background:var(--okbg);color:var(--ok)}.stp .dot{width:7px;height:7px;border-radius:50%;background:var(--ok);box-shadow:0 0 0 3px rgba(20,108,67,.18)}
table{width:100%;border-collapse:collapse}th{text-align:left;font:500 10.5px/1 var(--num);letter-spacing:.12em;text-transform:uppercase;color:var(--muted);padding:12px 20px;border-top:1px solid var(--line);border-bottom:1px solid var(--line)}td{padding:0 20px;height:52px;border-bottom:1px solid var(--line);font:400 14px var(--ui);color:var(--label)}td.mono{font:500 13px var(--num)}tbody tr:last-child td{border-bottom:0}
.plist,.nlist{list-style:none;margin:12px 0 0;padding:0}.plist li{display:grid;grid-template-columns:1fr auto auto;gap:16px;align-items:center;min-height:52px;border-top:1px solid var(--line)}.pct{display:flex;align-items:center;gap:6px;font:500 13px var(--num);color:var(--muted)}
.nlist li{display:flex;justify-content:space-between;align-items:center;gap:16px;padding:12px 0;border-top:1px solid var(--line)}
.sw2{width:40px;height:24px;border-radius:999px;background:var(--line2);position:relative;flex:none}.sw2 i{position:absolute;top:3px;left:3px;width:18px;height:18px;border-radius:50%;background:#fff;box-shadow:0 1px 2px rgba(1,31,74,.25);transition:transform 380ms var(--spring),width 200ms}.sw2.on{background:var(--navy)}.sw2.on i{transform:translateX(16px)}.sw2:active i{width:22px}
.ic-row{display:flex;gap:14px;align-items:center}.ic-b{width:44px;height:44px;border-radius:12px;background:var(--sunk);display:grid;place-items:center;color:var(--ink);flex:none}.foot{margin-top:14px}.lnk{color:var(--label);text-decoration:underline;text-underline-offset:3px}
.danger{max-width:860px;border:1px solid var(--line);border-radius:14px;background:var(--white);padding:0 20px}.danger summary{display:flex;align-items:center;gap:8px;height:52px;cursor:pointer;font:500 14px var(--ui);color:var(--err);list-style:none}.danger[open]{padding-bottom:18px}.danger[open] summary{border-bottom:1px solid var(--line);margin-bottom:14px}
.status{display:flex;gap:12px;align-items:flex-start;padding:14px 16px;border-radius:14px;border:1px solid}.status.ok{background:var(--okbg);border-color:var(--okln);color:var(--ok)}.status.warn{background:var(--warnbg);border-color:var(--warnln);color:var(--warn)}.status .b{color:inherit}.status .cap{color:inherit;opacity:.85}.status.alt{opacity:.55}
.steps{gap:26px}.steps button{gap:9px}.sn{width:22px;height:22px;border-radius:50%;display:grid;place-items:center;border:1.5px solid var(--line2);font:500 11px var(--num)!important;opacity:1!important}.steps button.on .sn{background:var(--navy);border-color:var(--navy);color:#fff}
.wiz{display:grid;grid-template-columns:minmax(0,1fr) 300px;gap:20px;align-items:start}.steps-v{min-width:0}.step{display:flex;flex-direction:column;gap:6px}.step[hidden]{display:none}.h2{font:600 22px/1.2 var(--num);letter-spacing:-.02em;color:var(--ink);margin:0 0 10px}
.plans{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.plans.m{grid-template-columns:1fr;margin-top:10px}
.plan{position:relative;display:flex;flex-direction:column;align-items:flex-start;gap:8px;padding:18px;border-radius:16px;border:1.5px solid var(--line);background:var(--white);text-align:left;transition:border-color 150ms,box-shadow 250ms,transform 320ms var(--spring)}.plan:hover{border-color:var(--line2)}.plan.sel{border-color:var(--navy);box-shadow:0 0 0 4px var(--focus)}
.pl-n{font:600 17px/1.2 var(--ui);color:var(--ink)}.plan .money em,.msum .money em{font:400 13px var(--ui);color:var(--muted);font-style:normal;margin-left:2px}.save{font:500 12px var(--num);color:var(--ok);background:var(--okbg);padding:2px 8px;border-radius:7px}
.pop{position:absolute;top:-11px;right:14px;padding:3px 10px;border-radius:999px;background:var(--navy);color:#fff;font:500 11px var(--num);letter-spacing:.06em;text-transform:uppercase}
.pl-cta{margin-top:auto;padding-top:6px;display:inline-flex;align-items:center;gap:6px;font:500 13.5px var(--ui);color:var(--label)}.plan.sel .pl-cta{color:var(--ink);font-weight:600}
.addons{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.addon{display:flex;flex-direction:column;align-items:flex-start;gap:8px;padding:16px;border-radius:16px;border:1.5px solid var(--line);background:var(--white);text-align:left}.addon.sel{border-color:var(--navy);box-shadow:0 0 0 4px var(--focus)}.addon.inc{background:var(--sunk);border-style:dashed}
.ad-top{display:flex;justify-content:space-between;align-items:center;width:100%;gap:8px}.pill{padding:3px 9px;border-radius:999px;background:var(--sunk);font:500 12px var(--ui);color:var(--muted)}.pill.on{background:var(--navy);color:#fff}.addon.inc .pill{background:var(--okbg);color:var(--ok)}.pain{font:400 12.5px var(--ui);color:var(--label);padding-left:10px;border-left:2px solid var(--line2)}.addon .money{margin-top:auto}
.renew{display:flex;gap:24px;padding:12px 16px;border-radius:12px;background:var(--sunk);font:400 13.5px var(--ui);color:var(--label)}.renew b{color:var(--ink);font-weight:500;margin-left:6px}.fld.doc{max-width:360px}
.pays{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:10px}.pay{display:flex;flex-direction:column;align-items:flex-start;gap:6px;padding:18px;border-radius:16px;border:1.5px solid var(--line);background:var(--white);text-align:left;color:var(--ink)}.pay:hover{border-color:var(--navy)}
.sum{text-align:left;position:sticky;top:16px;display:flex;flex-direction:column;gap:4px}.sum-t{display:flex;justify-content:space-between;align-items:baseline;margin:14px 0;padding-top:14px;border-top:1px solid var(--line)}.sum-acts{display:grid;grid-template-columns:auto 1fr;gap:8px}.sum-acts .btn{justify-content:center}
.cancel{display:flex;align-items:center;gap:12px;padding-top:6px}
.pixf{height:760px;position:relative;background:var(--paper)}.scrim{position:absolute;inset:0;background:rgba(1,31,74,.42)}.pixs{position:absolute;left:50%;top:40px;transform:translateX(-50%);width:440px;padding:22px 24px;border-radius:22px;background:var(--white);box-shadow:0 30px 70px -20px rgba(1,31,74,.45);display:flex;flex-direction:column;gap:12px;animation:swapin 380ms var(--spring)}
.pixs .x{position:absolute;top:14px;right:14px;width:36px;height:36px;border-radius:10px;font-size:22px;color:var(--muted)}.pix-h{display:flex;gap:12px}.pix-h .h2{margin:2px 0}
.wait{display:flex;align-items:center;gap:10px;padding:10px 12px;border-radius:12px;background:var(--sunk);font:500 13.5px var(--ui);color:var(--label)}.spin{width:16px;height:16px;border-radius:50%;border:2px solid var(--line2);border-top-color:var(--navy);animation:mspin .86s linear infinite}
.count{display:grid;grid-template-columns:auto 1fr;gap:2px 10px;align-items:baseline}.count b{font:600 22px var(--num);color:var(--ink);text-align:right}.count small{grid-column:1/-1}
.qr{align-self:center;display:grid;grid-template-columns:repeat(21,8px);grid-template-rows:repeat(21,8px);padding:12px;border:1px solid var(--line);border-radius:14px;background:#fff}.qr i{background:var(--navy);border-radius:1px}
.pix-acts{display:grid;grid-template-columns:1fr auto;gap:8px}.pix-acts .btn{justify-content:center}
.tools{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.tool{display:flex;flex-direction:column;gap:8px;padding:20px;border-radius:16px;border:1px solid var(--line);background:var(--white);color:inherit;text-decoration:none;transition:border-color 150ms,transform 320ms var(--spring)}.tool:hover{border-color:var(--line2)}.tool:active{transform:scale(.97)}.tool.off{opacity:.6;pointer-events:none}.tl-top{display:flex;justify-content:space-between;align-items:center;margin-bottom:6px}.note{margin-top:16px}
.m-body.scroll{overflow:auto;display:flex;flex-direction:column;gap:12px;padding-bottom:90px}.ptabs.sm{overflow-x:auto;gap:18px}.ptabs.sm button{font-size:14px}.sticky-save{margin-top:4px}
.dots{display:flex;gap:6px;justify-content:center}.dots i{width:7px;height:7px;border-radius:99px;background:var(--line2)}.dots i.on{width:22px;background:var(--navy)}
.msum{position:absolute;left:0;right:0;bottom:64px;display:flex;justify-content:space-between;align-items:center;gap:12px;padding:12px 16px;background:var(--white);border-top:1px solid var(--line);box-shadow:0 -10px 24px -18px rgba(1,31,74,.4)}.msum>div{display:flex;flex-direction:column}.frame.m{position:relative}
.plan .money,.plan-now .money{font:600 28px/1.1 var(--num);letter-spacing:-.02em;color:var(--ink)}.plan .money small,.plan-now .money small{font:500 13px var(--ui);color:var(--muted);margin-right:4px}
a.btn{text-decoration:none;color:inherit}a.btn.pri{color:#fff}
.wiz .sum{align-items:stretch}.sum-t{gap:10px}
.mrow{display:flex;align-items:baseline;gap:8px;margin:10px 0}.mstack{display:flex;flex-direction:column;gap:8px}.plan-now.m{display:block}
.inv{list-style:none;margin:0;padding:0 16px 6px}.inv li{display:flex;justify-content:space-between;align-items:center;padding:12px 0;border-top:1px solid var(--line)}.pad-x{display:block}
.mtop{margin-top:12px}.stp{align-self:flex-start;width:max-content}.m-body.scroll>*{flex-shrink:0}.danger.m{max-width:none;padding:0 16px}.danger.m[open]{padding-bottom:16px}.danger.m .btn{margin-top:12px}
.h2.m{font-size:19px;margin:6px 0 10px}.addons.m{grid-template-columns:1fr}.renew.m{gap:16px;font-size:13px}.pays.m{grid-template-columns:1fr}
.tot-m .money{margin-top:6px}.tools.m{grid-template-columns:1fr;display:grid;gap:10px}
.pixm .scrim{position:absolute;inset:0;background:rgba(1,31,74,.42);z-index:2}.bsheet{position:absolute;left:0;right:0;bottom:0;z-index:3;padding:10px 18px 84px;border-radius:24px 24px 0 0;background:var(--white);display:flex;flex-direction:column;gap:12px;animation:sheetup 420ms var(--spring)}.bsheet .grab{align-self:center;width:40px;height:5px;border-radius:9px;background:var(--line2)}.pixm .bn{position:absolute;left:0;right:0;bottom:0;z-index:4}
.qr.sm{grid-template-columns:repeat(21,7px);grid-template-rows:repeat(21,7px)}@keyframes sheetup{from{transform:translateY(60%)}}
.spin-i{animation:mspin .86s linear infinite}.morph-lite{justify-content:center}
'''
html=f'''<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Mockup · Conta</title><style>{fonts}{CSS}{EXTRA}{MOTION_CSS}</style></head><body>
<header class="doc"><p class="eyebrow">Zelo Design System · Fase 4 · mockup 05 de 06</p><h1>Perfil, Assinatura e Ferramentas</h1><p>Telas <code>/perfil</code> (hotspot), <code>/assinatura</code> (hotspot, cobrança) e <code>/ferramentas</code>. Tudo o que existe hoje continua: as 5 abas do perfil (Perfil, Empresa, Assinatura com histórico de faturas e portal de pagamentos, Preferências com impressão, plataformas, tabelas de preço e notificações, Integrações com operação offline e Zelo Impressão nos três estados), zona de perigo recolhida e a versão enxuta do subusuário. Na assinatura: avisos de origem (Mesas, Acessos, upgrade), status ativo ou teste, as 3 etapas (pacote, extensões com "já incluso" e aviso de perda de módulo, revisão com vencimento, CPF/CNPJ só quando falta, Pix ou cartão), resumo com total, barra fixa no celular, cancelar e o Pix com QR, contagem, copia e cola e "Já paguei". Nenhuma regra de cobrança muda; só apresentação.</p>
<ol><li><b>Perfil</b>: abas com indicador líquido, cartões por assunto, "Salvar alterações" vira loader → check.</li><li><b>Assinatura</b>: etapas como abas, cartões de pacote com seleção em navy, resumo lateral com o total que conta ao mudar.</li><li><b>Pix</b>: sheet com QR, contagem regressiva em Mono e cópia com check.</li><li><b>Ferramentas</b>: cartões com aperto no toque; Precificação e Cardápio seguem os padrões aprovados.</li></ol>
<p class="hint-motion">Com movimento: troque as abas do perfil, clique nas etapas e nos pacotes/extensões (o total conta), nos interruptores, em "Salvar" e em "Copiar código Pix".</p></header>
<section class="row"><h2 class="cap-h">1 · Perfil — desktop 1440 (troque as abas)</h2>{PERFIL_D}</section>
<section class="row"><h2 class="cap-h">2 · Assinatura — desktop 1440 (clique nas etapas e nos pacotes)</h2>{ASSIN_D}</section>
<section class="row"><h2 class="cap-h">3 · Pix — sheet</h2>{PIX}</section>
<section class="row"><h2 class="cap-h">4 · Ferramentas — desktop 1440</h2>{FERR_D}</section>
<section class="row mob"><div><h2 class="cap-h">5 · Perfil — celular 390</h2>{MOB_P}</div><div><h2 class="cap-h">6 · Assinatura — celular 390</h2>{MOB_A}</div></section>
<section class="row mob"><div><h2 class="cap-h">7 · Perfil · Empresa</h2>{M_EMP}</div><div><h2 class="cap-h">8 · Perfil · Assinatura</h2>{M_ASS}</div><div><h2 class="cap-h">9 · Perfil · Preferências</h2>{M_PREF}</div></section>
<section class="row mob"><div><h2 class="cap-h">10 · Integrações + zona de perigo</h2>{M_INT}</div><div><h2 class="cap-h">11 · Subusuário · Minha conta</h2>{M_SUB}</div><div><h2 class="cap-h">12 · Ferramentas</h2>{M_FERR}</div></section>
<section class="row mob"><div><h2 class="cap-h">13 · Assinatura · Extensões</h2>{M_STEP2}</div><div><h2 class="cap-h">14 · Assinatura · Pagamento</h2>{M_STEP3}</div><div><h2 class="cap-h">15 · Pix em sheet</h2>{M_PIX}</div></section>
{MOTION_JS}<script>
document.querySelectorAll('.cnt').forEach((el) => {{ const to = parseFloat(el.dataset.to); zCount(el, 0, to); }});
document.querySelectorAll('.sw2').forEach((b) => b.addEventListener('click', () => {{ b.classList.toggle('on'); b.setAttribute('aria-checked', b.classList.contains('on')); }}));
// perfil tabs → blur swap
document.querySelectorAll('.ptabs button[data-go]').forEach((b) => b.addEventListener('click', () => {{ const panes = b.closest('main').querySelector('.panes'); zSwap(panes, () => panes.querySelectorAll('.pane').forEach((p) => p.hidden = p.dataset.t !== b.dataset.go)); }}));
// assinatura wizard
const wiz = document.querySelector('#assin'); let step = 1;
const tabs = wiz.querySelectorAll('.steps button');
const go = (n) => {{ step = Math.max(1, Math.min(3, n)); tabs[step - 1].click(); }};
tabs.forEach((b) => b.addEventListener('click', () => {{ step = +b.dataset.step; const v = wiz.querySelector('.steps-v'); zSwap(v, () => v.querySelectorAll('.step').forEach((s) => s.hidden = +s.dataset.s !== step)); wiz.querySelector('[data-next]').textContent = step === 1 ? 'Continuar' : step === 2 ? 'Revisar e pagar' : 'Escolha Pix ou cartão'; }}));
wiz.querySelector('[data-next]').addEventListener('click', () => go(step + 1)); wiz.querySelector('[data-back]').addEventListener('click', () => go(step - 1));
const tot = wiz.querySelector('#tot'); let cur = 228;
const recalc = () => {{ const base = +wiz.querySelector('.plan.sel').dataset.price; const add = [...wiz.querySelectorAll('.addon.sel')].reduce((a, x) => a + +x.dataset.price, 0); const nv = base + add; zCount(tot, cur, nv); cur = nv; }};
wiz.querySelectorAll('.plan').forEach((p) => p.addEventListener('click', () => {{ wiz.querySelectorAll('.plan').forEach((x) => {{ x.classList.remove('sel'); x.querySelector('.pl-cta').textContent = 'Escolher pacote'; }}); p.classList.add('sel'); p.querySelector('.pl-cta').textContent = 'Novo pacote selecionado'; recalc(); }}));
wiz.querySelectorAll('.addon:not(.inc)').forEach((a) => a.addEventListener('click', () => {{ a.classList.toggle('sel'); const on = a.classList.contains('sel'); const pill = a.querySelector('.pill'); pill.textContent = on ? 'Selecionado' : 'Opcional'; pill.classList.toggle('on', on); recalc(); }}));
// button → loader → check
document.querySelectorAll('.morph-lite').forEach((b) => b.addEventListener('click', (e) => {{ e.preventDefault(); if (b.dataset.busy) return; const html = b.innerHTML; b.dataset.busy = 1; b.style.minWidth = b.offsetWidth + 'px'; b.innerHTML = '<svg class="ic spin-i" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round"><circle cx="12" cy="12" r="9" opacity=".2"/><path d="M12 3a9 9 0 0 1 9 9"/></svg>'; setTimeout(() => {{ b.innerHTML = '<svg class="ic popin" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12.5l4.5 4.5L19 7.5"/></svg>'; }}, 800); setTimeout(() => {{ b.innerHTML = html; delete b.dataset.busy; }}, 1900); }}));
// Pix countdown
const cd = document.querySelector('#cd'); let secs = 14 * 60 + 32; setInterval(() => {{ secs = Math.max(0, secs - 1); cd.textContent = String(Math.floor(secs / 60)).padStart(2, '0') + ':' + String(secs % 60).padStart(2, '0'); }}, 1000);
</script></body></html>'''
open('/home/user/zelopdv/docs/design-system/mockups/05-conta.html','w').write(html)
print('ok', len(html))
