import sys; sys.path.insert(0, '/home/user/zelopdv/docs/design-system/mockups')
from _mk import fonts, i, money, sidebar, CSS, ICON, MOTION_CSS, MOTION_JS, morph_cta
ICON.update({'check':'<path d="m5 12 5 5 9-10"/>','circle':'<circle cx="12" cy="12" r="8"/>','refresh':'<path d="M20 11a8 8 0 0 0-14.9-4M4 13a8 8 0 0 0 14.9 4"/><path d="M5 3v4h4M19 21v-4h-4"/>','filter':'<path d="M4 5h16l-6 7v6l-4 2v-8L4 5Z"/>','sort':'<path d="M7 4v16M3 16l4 4 4-4M17 20V4M13 8l4-4 4 4"/>','edit':'<path d="M5 19h4l10-10-4-4L5 15v4Z"/>','alert':'<path d="M12 4 2.5 20h19L12 4Z"/><path d="M12 10v4M12 17h.01"/>','up':'<path d="M7 17 17 7M9 7h8v8"/>','chevr':'<path d="m9 6 6 6-6 6"/>','cake':'<path d="M4 20h16v-7H4v7Z"/><path d="M4 16c2 1 4-1 6 0s4 1 6 0 3-1 4 0M12 8v5M12 4v1"/>','phone':'<path d="M5 4h4l2 5-3 2a11 11 0 0 0 5 5l2-3 5 2v4a2 2 0 0 1-2 2A16 16 0 0 1 3 6a2 2 0 0 1 2-2Z"/>'})
def num(v, dec=2): return f'<span class="cnt" data-to="{v}" data-dec="{dec}">{f"{v:,.{dec}f}".replace(",","X").replace(".",",").replace("X",".")}</span>'
KPI=f'''<div class="kpis">
<div class="kpi hero"><p class="eyebrow">Vendas do caixa #12</p><p class="money xl"><small>R$</small>{num(2418)}</p><p class="cap">34 cupons no caixa atual</p></div>
<div class="kpi"><p class="eyebrow">Ticket médio</p><p class="money md"><small>R$</small>{num(71.12)}</p><p class="cap">34 cupons</p></div>
<div class="kpi"><p class="eyebrow">Caixa</p><p class="kv"><i class="dot ok"></i>Aberto</p><p class="cap">Desde 08:00 · 6h12</p></div>
<div class="kpi"><p class="eyebrow">Estoque</p><p class="kv warn">{i("alert",20)}2 críticos</p><p class="cap">Itens abaixo do mínimo</p></div></div>'''
SETUP='''<section class="card setup"><div class="setup-h"><div><h2 class="heading">Terminar de configurar</h2><p class="cap">Nada disso trava o caixa. Faça quando sobrar um tempo.</p></div><span class="prog"><b>2</b>/4</span></div>
<ul class="chk"><li class="done"><span class="ck">✓</span>CPF ou CNPJ no recibo</li><li class="done"><span class="ck">✓</span>Largura da bobina — 80 mm</li><li><span class="ck"></span>Cadastrar seu primeiro produto<button class="lnk">Cadastrar</button></li><li><span class="ck"></span>Logo da loja no recibo<button class="lnk">Enviar logo</button></li></ul></section>'''
ACT=[('14:32','Venda #1042','Pix',87.4),('14:25','Venda #1041','Dinheiro',24.9),('14:12','Venda #1040','Crédito',112.0),('13:58','Sangria','Retirada p/ cofre',-200.0),('13:40','Venda #1039','Fiado · Marina',36.5)]
ACTIV='<section class="card act"><div class="card-h"><h2 class="heading">Atividade recente</h2><button class="lnk">Ver relatório completo'+i('chevr',14)+'</button></div><ul class="actlist">'+''.join(f'<li><span class="t">{t}</span><span class="nm">{n}<small>{d}</small></span>{money(abs(v),"sm " + ("neg" if v<0 else ""))}</li>' for t,n,d,v in ACT)+'</ul></section>'
QUICK=f'<div class="quick"><button class="qa pri">{i("bag")}Nova venda<span class="kbd inv">F9</span></button><button class="qa">{i("chart")}Relatórios</button><button class="qa">{i("users")}Clientes</button><button class="qa">{i("box")}Produtos</button></div>'
DASH_D=f'''<div class="frame d"><div class="app">{sidebar('Dashboard')}<main class="main">
<header class="ph"><div><p class="eyebrow">Gestão / Dashboard</p><h1 class="title">Dashboard</h1></div><button class="btn out">{i("refresh")}Atualizar</button></header>
{KPI}<div class="dgrid">{ACTIV}<div class="dcol">{SETUP}{QUICK}</div></div></main></div></div>'''
PR=[('Açaí 500ml','Doces',18.0,'2 grupos','Não controla',True),('Beirute de frango','Lanches',32.0,'—','Não controla',True),('Bolo de cenoura (fatia)','Doces',8.9,'—','12 un.',True),('Coca-Cola 600ml','Bebidas',9.5,'—','2 un.',True),('Coxinha de frango','Salgados',7.5,'—','48 un.',True),('Esfiha de carne','Salgados',6.5,'—','3 un.',True),('Pão de queijo','Salgados',5.0,'—','Não controla',False),('X-Bacon','Lanches',29.9,'1 grupo','Não controla',True)]
def st(s):
    if s.endswith('un.') and int(s.split()[0])<=3: return f'<span class="stk low">{s}</span>'
    return f'<span class="stk">{s}</span>' if s!='Não controla' else f'<span class="stk off">{s}</span>'
rows=''.join(f'<tr><td><span class="cb"></span></td><td class="pn">{n}{"<small>Oculto no PDV</small>" if not on else ""}</td><td>{c}</td><td>{money(p,"sm")}</td><td class="cx">{g}</td><td>{st(s)}</td><td><button class="sw2 {"on" if on else ""}" aria-label="Ativo"><i></i></button></td><td><button class="icon-btn sm">{i("edit",16)}</button></td></tr>' for n,c,p,g,s,on in PR)
CATS=''.join(f'<li class="{"on" if n=="Todos os produtos" else ""}"><span>{n}</span><b>{k}</b></li>' for n,k in [('Todos os produtos',14),('Lanches',5),('Bebidas',3),('Salgados',3),('Doces',3)])
PROD_D=f'''<div class="frame d"><div class="app">{sidebar('Produtos')}<main class="main">
<header class="ph"><div><p class="eyebrow">Gestão / Produtos</p><h1 class="title">Produtos</h1></div><div class="acts"><button class="btn out">{i("sort")}Ações</button><button class="btn pri">{i("plus")}Novo produto</button></div></header>
<div class="pgl"><aside class="cats card"><div class="card-h"><p class="eyebrow">Categorias</p><button class="icon-btn sm">{i("plus",16)}</button></div><ul>{CATS}</ul></aside>
<section class="card tbl"><div class="tbl-h"><div class="tabs"><button class="on">Todos<span>14</span></button><button>Ativos<span>13</span></button><button>Ocultos no PDV<span>1</span></button><button>Com estoque<span>4</span></button></div><div class="search sm">{i("search")}<span>Buscar por nome, código ou categoria</span></div></div>
<table><thead><tr><th></th><th>Produto</th><th>Categoria</th><th>Preço</th><th>Complementos</th><th>Estoque</th><th>Ativo</th><th></th></tr></thead><tbody>{rows}</tbody></table>
<div class="pag"><span class="cap">Mostrando 1–8 de 14</span><div class="pgb"><button class="btn out sm">Anterior</button><b>1</b><button class="btn out sm">2</button><button class="btn out sm">Próxima</button></div></div></section></div></main></div></div>'''
PE=[('Marina Souza','Cliente','(11) 99999-0001','12/03',86.5,'deve'),('Carlos Lima','Cliente','(11) 98888-2020','—',0,'ok'),('Distribuidora Sol','Fornecedor','(11) 3333-4444','—',0,'ok'),('Beto','Funcionário','(11) 97777-1212','28/09',0,'ok'),('Joana Reis','Cliente','(11) 96666-3434','—',24.9,'deve')]
prow=''.join(f'<tr><td class="pn"><span class="avs">{n[0]}</span>{n}</td><td><span class="tag">{t}</span></td><td class="mono">{c}</td><td class="mono">{b}</td><td>{f"<span class=fd>{money(f,chr(115)+chr(109))}</span>" if f else "<span class=stk>Em dia</span>"}</td><td><button class="icon-btn sm">{i("edit",16)}</button></td></tr>' for n,t,c,b,f,_ in PE)
PES_D=f'''<div class="frame d"><div class="app">{sidebar('Pessoas')}<main class="main">
<header class="ph"><div><p class="eyebrow">Gestão / Pessoas</p><h1 class="title">Pessoas</h1></div><button class="btn pri">{i("plus")}Nova pessoa</button></header>
<div class="lst-bar"><div class="tabs"><button class="on">Todos<span>48</span></button><button>Clientes<span>41</span></button><button>Fornecedores<span>4</span></button><button>Funcionários<span>3</span></button></div><div class="search sm">{i("search")}<span>Buscar por nome ou contato</span></div><button class="chip-f">{i("filter",15)}Com fiado em aberto</button></div>
<section class="card tbl"><table><thead><tr><th>Nome</th><th>Tipo</th><th>Contato</th><th>Aniversário</th><th>Fiado</th><th></th></tr></thead><tbody>{prow}</tbody></table></section>
<p class="cap note">Mesmo padrão para Estoque, Despesas, Fichário e Mesas (cadastro): cabeçalho com título em Mono, abas com contagem, busca, filtros em chip, tabela em cartão, ação primária no topo.</p></main></div></div>'''
PROD_M=f'''<div class="frame m"><div class="mh"><div><p class="mh-t">Produtos</p><p class="mh-s">14 produtos · 5 categorias</p></div><button class="icon-btn nav r">{i("plus")}</button></div>
<div class="m-body"><div class="search">{i("search")}<span>Buscar produto</span></div><div class="tabs sm"><button class="on">Todos<span>14</span></button><button>Lanches<span>5</span></button><button>Bebidas<span>3</span></button><button>Salgados<span>3</span></button></div>
<ul class="mlist">{''.join(f'<li><div><p class="pn">{n}</p><p class="cap">{c} · {st(s)}</p></div>{money(p,"sm")}<button class="sw2 {"on" if on else ""}"><i></i></button></li>' for n,c,p,g,s,on in PR[:7])}</ul></div>
<nav class="bn"><a>{i('bag')}PDV</a><a class="on">{i('grid')}Gestão</a><a>{i('wallet')}Financeiro</a><a>{i('dots')}Outros</a><a>{i('user')}Perfil</a></nav></div>'''
DASH_M=f'''<div class="frame m"><div class="mh"><div><p class="mh-t">Dashboard</p><p class="mh-s">Caixa #12 aberto · 6h12</p></div></div>
<div class="m-body"><div class="kpis m"><div class="kpi hero"><p class="eyebrow">Vendas do caixa</p><p class="money xl"><small>R$</small>{num(2418)}</p><p class="cap">34 cupons no caixa atual</p></div><div class="kpi"><p class="eyebrow">Ticket médio</p><p class="money md"><small>R$</small>{num(71.12)}</p></div><div class="kpi"><p class="eyebrow">Estoque</p><p class="kv warn sm">{i("alert",16)}2 críticos</p></div></div>{QUICK}</div>
<nav class="bn"><a>{i('bag')}PDV</a><a class="on">{i('grid')}Gestão</a><a>{i('wallet')}Financeiro</a><a>{i('dots')}Outros</a><a>{i('user')}Perfil</a></nav></div>'''
EXTRA='''
.btn.pri{background:var(--navy);color:#fff;border:0}.btn.sm{height:34px;padding:0 10px;font-size:12.5px}.acts{display:flex;gap:8px}
.card{background:var(--white);border:1px solid var(--line);border-radius:14px}.card-h{display:flex;justify-content:space-between;align-items:center;padding:16px 18px 10px}
.kpis{display:grid;grid-template-columns:1.4fr 1fr 1fr 1fr;gap:12px;margin-bottom:16px}.kpis.m{grid-template-columns:1fr 1fr;margin-bottom:14px}.kpis.m .hero{grid-column:1/-1}
.kpi{background:var(--white);border:1px solid var(--line);border-radius:14px;padding:16px;display:flex;flex-direction:column;gap:8px}.kpi.hero{background:var(--navy);border-color:var(--navy);color:#fff}.kpi.hero .eyebrow{color:rgba(255,255,255,.6)}.kpi.hero .money small{color:rgba(255,255,255,.6)}.kpi.hero .cap{color:rgba(255,255,255,.7)}
.up{display:inline-flex;align-items:center;gap:2px;font:500 12px var(--num);color:#4ADE80}.kpi:not(.hero) .up{color:var(--ok)}
.kv{display:flex;align-items:center;gap:8px;font:600 22px/1.1 var(--num);letter-spacing:-.02em}.kv.sm{font-size:17px}.kv.warn{color:var(--warn)}.dot{width:9px;height:9px;border-radius:50%}.dot.ok{background:var(--ok);box-shadow:0 0 0 4px var(--okbg)}
.dgrid{display:grid;grid-template-columns:minmax(0,1.3fr) minmax(0,1fr);gap:16px;flex:1;min-height:0}.dcol{display:flex;flex-direction:column;gap:16px}
.actlist{list-style:none;margin:0;padding:0 18px 12px}.actlist li{display:grid;grid-template-columns:52px 1fr auto;gap:10px;align-items:center;padding:11px 0;border-top:1px solid var(--line)}.actlist .t{font:500 12.5px var(--num);color:var(--muted)}.actlist .nm{font:500 14.5px var(--ui)}.actlist .nm small{display:block;font:400 12px var(--ui);color:var(--muted)}.money.neg{color:var(--err)}.money.neg::before{content:'−';margin-right:2px}
.lnk{display:inline-flex;align-items:center;gap:4px;font:500 13px var(--ui);color:var(--label);text-decoration:underline;text-underline-offset:3px}
.setup{padding:16px 18px}.chk li{flex-wrap:nowrap}.chk li>span:not(.ck){flex:1}.setup-h{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:8px}.prog{font:500 13px var(--num);color:var(--muted)}.prog b{color:var(--ink);font-size:18px}
.chk{list-style:none;margin:0;padding:0}.chk li{display:flex;align-items:center;gap:10px;min-height:40px;border-top:1px solid var(--line);font:500 14px var(--ui)}.chk li .lnk{margin-left:auto}.ck{width:20px;height:20px;border-radius:50%;border:1.5px solid var(--line2);display:grid;place-items:center;font:600 11px var(--ui);color:#fff}.chk li.done{color:var(--muted);text-decoration:line-through}.chk li.done .ck{background:var(--ok);border-color:var(--ok)}
.quick{display:grid;grid-template-columns:1fr 1fr;gap:8px}.qa{display:flex;align-items:center;gap:10px;height:56px;padding:0 16px;border-radius:14px;border:1px solid var(--line);background:var(--white);font:500 14.5px var(--ui)}.qa.pri{background:var(--navy);border-color:var(--navy);color:#fff;grid-column:1/-1}.qa .kbd{margin-left:auto}
.pgl{display:grid;grid-template-columns:240px 1fr;gap:16px;flex:1;min-height:0}.cats ul{list-style:none;margin:0;padding:4px 8px 12px}.cats li{display:flex;justify-content:space-between;align-items:center;height:38px;padding:0 10px;border-radius:10px;font:500 14px var(--ui);color:var(--label)}.cats li b{font:500 12px var(--num);color:var(--muted)}.cats li.on{background:var(--sunk);color:var(--ink)}
.tbl{display:flex;flex-direction:column;overflow:hidden}.tbl-h{display:flex;justify-content:space-between;align-items:flex-end;gap:16px;padding:6px 18px 0}.tbl-h .tabs{box-shadow:none}.search.sm{height:40px;margin:0 0 8px;width:320px}
table{width:100%;border-collapse:collapse}th{text-align:left;font:500 10.5px/1 var(--num);letter-spacing:.12em;text-transform:uppercase;color:var(--muted);padding:12px 14px;border-top:1px solid var(--line);border-bottom:1px solid var(--line)}td{padding:0 14px;height:56px;border-bottom:1px solid var(--line);font:400 14px var(--ui);color:var(--label)}tbody tr{transition:background 150ms}tbody tr:hover{background:var(--paper)}
td.pn,.pn{font:500 14.5px var(--ui);color:var(--ink)}td.pn small{display:block;font:400 12px var(--ui);color:var(--warn)}td.cx{font:500 13px var(--ui)}td.mono{font:500 13px var(--num)}
.cb{display:inline-block;width:18px;height:18px;border-radius:5px;border:1.5px solid var(--line2)}
.stk{display:inline-flex;height:24px;align-items:center;padding:0 8px;border-radius:7px;background:var(--sunk);font:500 12px var(--num);color:var(--label)}.stk.off{background:none;color:var(--muted);font-family:var(--ui)}.stk.low{background:var(--warnbg);color:var(--warn)}
.sw2{width:40px;height:24px;border-radius:999px;background:var(--line2);position:relative}.sw2 i{position:absolute;top:3px;left:3px;width:18px;height:18px;border-radius:50%;background:#fff;box-shadow:0 1px 2px rgba(1,31,74,.25);transition:transform 380ms var(--spring)}.sw2.on{background:var(--navy)}.sw2.on i{transform:translateX(16px)}
.icon-btn.sm{width:32px;height:32px;background:none;color:var(--muted)}
.pag{display:flex;justify-content:space-between;align-items:center;padding:12px 18px;margin-top:auto}.pgb{display:flex;gap:6px;align-items:center}.pgb b{width:34px;height:34px;border-radius:9px;background:var(--navy);color:#fff;display:grid;place-items:center;font:500 13px var(--num)}
.lst-bar{display:flex;align-items:flex-end;gap:12px;margin-bottom:12px}.lst-bar .tabs{flex:1}.chip-f{display:inline-flex;gap:6px;align-items:center;height:40px;padding:0 12px;border-radius:999px;border:1px solid var(--line);background:var(--white);font:500 13px var(--ui);margin-bottom:8px}
.avs{display:inline-grid;place-items:center;width:30px;height:30px;border-radius:50%;background:var(--sunk);font:500 12px var(--num);margin-right:10px}.tag{padding:3px 8px;border-radius:7px;background:var(--sunk);font:500 12px var(--ui)}.fd .money{color:var(--warn)}.fd .money small{color:inherit}
.note{margin-top:14px}
.mlist{list-style:none;margin:12px 0 0;padding:0;background:var(--white);border:1px solid var(--line);border-radius:14px}.mlist li{display:grid;grid-template-columns:1fr auto auto;gap:12px;align-items:center;padding:12px 14px;border-bottom:1px solid var(--line)}.mlist li:last-child{border:0}.mlist .cap{display:flex;gap:6px;align-items:center}
'''
html=f'''<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Mockup · Gestão</title><style>{fonts}{CSS}{EXTRA}{MOTION_CSS}</style></head><body>
<header class="doc"><p class="eyebrow">Zelo Design System · Fase 4 · mockup 03 de 06</p><h1>Gestão</h1><p>Dashboard (<code>/gestao</code>), Produtos (<code>/gestao/produtos</code>, hotspot) e o padrão das listas (Pessoas, Estoque, Despesas, Fichário, cadastro de Mesas). Mesmas funções e os mesmos dados de hoje (nada novo é buscado); só apresentação. Bottom nav original do celular.</p>
<ol><li><b>Dashboard</b> — vendas do caixa em destaque (número que conta), ticket médio, estado do caixa e do estoque; atividade recente; "Terminar de configurar" com progresso; atalhos com "Nova venda" em destaque.</li><li><b>Produtos</b> — categorias à esquerda com contagem; tabela em cartão com abas de filtro (indicador líquido), busca, estoque com alerta em âmbar, interruptor "Ativo" com mola, paginação.</li><li><b>Listas</b> — Pessoas como modelo do padrão: abas com contagem, busca, filtro em chip, tabela em cartão.</li><li><b>Celular</b> — dashboard compacto e produtos em lista com interruptor.</li></ol>
<p class="hint-motion">Com movimento: números contam ao abrir; clique nas abas (indicador líquido), nos interruptores "Ativo" (mola) e em qualquer botão/linha (aperto).</p></header>
<section class="row"><h2 class="cap-h">1 · Dashboard — desktop 1440</h2>{DASH_D}</section>
<section class="row"><h2 class="cap-h">2 · Produtos — desktop 1440</h2>{PROD_D}</section>
<section class="row"><h2 class="cap-h">3 · Listas (Pessoas) — desktop 1440</h2>{PES_D}</section>
<section class="row mob"><div><h2 class="cap-h">4 · Dashboard — celular 390</h2>{DASH_M}</div><div><h2 class="cap-h">5 · Produtos — celular 390</h2>{PROD_M}</div></section>
<script>
document.querySelectorAll('.sw2').forEach((b) => b.addEventListener('click', () => b.classList.toggle('on')));
</script>{MOTION_JS}<script>
document.querySelectorAll('.cnt').forEach((el) => {{ const to = parseFloat(el.dataset.to); zCount(el, 0, to); }});
</script></body></html>'''
open('/home/user/zelopdv/docs/design-system/mockups/03-gestao.html','w').write(html)
