-- Keep the admin PIN server-only. Browser profile consumers retain access to
-- every existing profile column except empresa_perfil.pin_admin.
-- The exact pre-change ACL/policy snapshot and rollback are documented in
-- docs/operations/EMPRESA-PERFIL-PIN-SELECT-SNAPSHOT-2026-08-13.md.

revoke select on table public.empresa_perfil
from anon, authenticated;

grant select (
  id,
  user_id,
  nome_exibicao,
  documento,
  inscricao_estadual,
  endereco,
  contato,
  timezone,
  logo_url,
  rodape_recibo,
  largura_bobina,
  created_at,
  updated_at,
  modulo_pdv_ativo,
  modulo_delivery_ativo,
  razao_social,
  plataformas_pagamento,
  last_seen_at,
  onboarding_completed,
  chave_pix,
  manager_phone,
  horario_abertura,
  horario_fechamento,
  dias_fechamento,
  ai_instructions,
  blocked_dates,
  manager_history,
  tipo_negocio,
  zelochat_onboarding_done,
  ai_enabled,
  webhook_token,
  ai_can_reengage_pending,
  zelochat_disabled_builtin_triggers,
  delivery_config,
  whatsmiau_instance,
  whatsmiau_connected,
  whatsmiau_phone,
  notify_customer_preparing,
  notify_customer_ready,
  notify_customer_out_for_delivery,
  pix_receipt_config,
  ai_mode,
  ai_schedule_start,
  ai_schedule_end,
  zelochat_mode,
  zelochat_internal_send_key_hash,
  zelochat_onboarding_done_at,
  tabelas_preco_ativo,
  tabela_preco_1_nome,
  tabela_preco_2_nome,
  tabela_preco_3_nome,
  referral_code,
  deletion_scheduled_at,
  deletion_requested_at,
  deletion_source,
  ai_schedule_days,
  zelomenu_slug,
  zelomenu_welcome_text,
  zelomenu_featured_enabled,
  zelomenu_featured_product_ids,
  zelomenu_category_order,
  intelligence_enabled_at,
  gerente_prefs,
  gerente_whatsapp_last_sent_date,
  horario_semanal,
  zelomenu_recommendations_enabled,
  zelomenu_recommendation_product_ids,
  zelomenu_category_suggestions,
  zelomenu_pix_key_type,
  zelomenu_auto_accept_orders,
  delivery_postal_code,
  delivery_number,
  delivery_complement,
  delivery_street,
  delivery_neighborhood,
  delivery_city,
  delivery_state,
  delivery_latitude,
  delivery_longitude,
  delivery_location_version,
  zelomenu_cover_url,
  zelomenu_description,
  zelomenu_sponsored_enabled,
  origem_aquisicao,
  zelomenu_scheduling_enabled,
  zelomenu_scheduling_lead_time_minutes
)
on table public.empresa_perfil
to authenticated;
